# Netlify Configuration for Static Site
[build]
  # Base directory for the build
  base = "."
  
  # Publish directory (root of the repository)
  publish = "."
  
  # No build command needed for static site
  command = ""
  
  # Environment variables (if any)
  [build.environment]
    # Set Node.js version (not used but prevents auto-detection)
    NODE_VERSION = "18"
    
    # Disable unnecessary processing
    NPM_FLAGS = "--no-optional"
    
# Disable build plugins that might interfere
[build.processing]
  skip_processing = true

# Explicitly set as a static site
[build.processing.html]
  pretty_urls = true
  
[build.processing.images]
  compress = true

[[redirects]]
  from = "/voting.html"
  to = "/voting.html"
  status = 200

[[redirects]]
  from = "/leaderboard.html"
  to = "/leaderboard.html"
  status = 200

[[redirects]]
  from = "/admin.html"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/thank-you.html"
  to = "/thank-you.html"
  status = 200

# Form configuration for voting form
[forms."voting"]
  fields = [
    "firstName",
    "lastName",
    "email",
    "totalCandidates"
  ]
