[build]
  publish = "."
  command = "echo 'Static site - no build required'"

# No Node.js environment needed for static site
# NODE_VERSION removed as it's not required

[[redirects]]
  from = "/voting.html"
  to = "/voting.html"
  status = 200

[[redirects]]
  from = "/leaderboard.html"
  to = "/leaderboard.html"
  status = 200

[[redirects]]
  from = "/admin.html"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/thank-you.html"
  to = "/thank-you.html"
  status = 200

# Form configuration for voting form
[forms."voting"]
  fields = [
    "firstName",
    "lastName",
    "email",
    "totalCandidates"
  ]
