[build]
  # Use the build script
  command = "./build.sh"
  
  # Publish from the build directory
  publish = "build"
  
  # Base directory
  base = "."

# Environment settings
[build.environment]
  NODE_VERSION = "18"

# Disable unnecessary processing
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true
  
[build.processing.images]
  compress = true

# Redirects
[[redirects]]
  from = "/voting.html"
  to = "/voting.html"
  status = 200

[[redirects]]
  from = "/leaderboard.html"
  to = "/leaderboard.html"
  status = 200

[[redirects]]
  from = "/admin.html"
  to = "/admin.html"
  status = 200

# Form configuration
[forms."voting"]
  fields = [
    "firstName",
    "lastName", 
    "email",
    "totalCandidates"
  ]
