[build]
  # Publish directory (Netlify will serve files from here)
  publish = "."
  
  # No build command needed for static site
  command = ""

# Basic redirects and headers
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' https:;"
  
[build.processing.images]
  compress = true

# Redirects
[[redirects]]
  from = "/voting.html"
  to = "/voting.html"
  status = 200

[[redirects]]
  from = "/leaderboard.html"
  to = "/leaderboard.html"
  status = 200

[[redirects]]
  from = "/admin.html"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/dashboard.html"
  to = "/dashboard.html"
  status = 200

# Form configuration
[forms."voting"]
  fields = [
    "firstName",
    "lastName", 
    "email",
    "totalCandidates"
  ]
