[build]
  publish = "."
  command = "echo 'No build process needed for static site' && exit 0"

# Explicitly disable Node.js build environment
# This is a pure static HTML/JS/CSS site

[[redirects]]
  from = "/voting.html"
  to = "/voting.html"
  status = 200

[[redirects]]
  from = "/leaderboard.html"
  to = "/leaderboard.html"
  status = 200

[[redirects]]
  from = "/admin.html"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/thank-you.html"
  to = "/thank-you.html"
  status = 200

# Form configuration for voting form
[forms."voting"]
  fields = [
    "firstName",
    "lastName",
    "email",
    "totalCandidates"
  ]
