[build]
  # Publish from the root directory
  publish = "/"
  functions = "netlify/functions"
  command = ""

# Environment settings
[build.environment]
  NODE_VERSION = "18"

# Handle form submissions
[[redirects]]
  from = "/submit-vote"
  to = "/.netlify/functions/submit-vote"
  status = 200
  force = true

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
  
[build.processing.images]
  compress = true

# Redirects
[[redirects]]
  from = "/voting.html"
  to = "/voting.html"
  status = 200

[[redirects]]
  from = "/leaderboard.html"
  to = "/leaderboard.html"
  status = 200

[[redirects]]
  from = "/admin.html"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/dashboard.html"
  to = "/dashboard.html"
  status = 200

# Form configuration
[forms."voting"]
  fields = [
    "firstName",
    "lastName", 
    "email",
    "totalCandidates"
  ]
